# Generated by Django 4.2.8 on 2023-12-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='just_user',
            field=models.BooleanField(default=True),
        ),
    ]
